use_frameworks!

platform :ios, '8.0'

target 'CountDownButton_Example' do
  pod 'CountDownButton', :path => '../'

  target 'CountDownButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
